language: node_js
dist: trusty
sudo: true
node_js:
  - "node"
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ] ; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq emacs-snapshot ;
    fi
  - if [ "$EMACS" = 'emacs24' ] ; then
      sudo apt-get install -qq emacs24;
    fi
script:
  - ./test-travis.sh
  
