#language: emacs-lisp
language: python
sudo: false
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=snapshot
before_install:
- make setup-CI
install:
- make install
script:
- make --keep-going test
notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b1163bae60c65660fbd2
    on_success: change
    on_failure: always
    on_start: never
